# -*- coding: utf-8 -*-
"""Projeto_01_EBAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rkaah8jJFS84c46wGh2dDiBa4vKooBge
"""

nome_usuario = input("Olá!, como eu posso te chamar: ")
print("OK ", nome_usuario,""" essa calculadora serve para converter os valores
de temperatura EM CELSIUS para Kelvin ou Fahrenheit, conforme a sua necessidade,
basta inserir o valor da temperatura, a unidade de medida dela e para qual unidade
de medida você quer que ela esteja, lembrando que Celsius é representado pro C,
Kelvin por K e Fahrenheit por F (Esta calculadora funciona somente para a conversão
de Celsius para as duas outras unidades)""")

temp = input("Quantos graus vamos converter: ")
unidade_medida1 = input("Em qual unidade de medida ela esta? ").upper() #Utilizei o .upper para a entrada do usuario ser sempre maiscula
unidade_medida2= input("Em qual unidade de media você quer que ela esteja? ").upper()
temp_int = int(temp)


if unidade_medida1 == "C" and unidade_medida2 =="K":
  print(nome_usuario, temp,unidade_medida1,"°", "é equivalente a", temp_int + 273,"°k")
elif unidade_medida1 == "C" and unidade_medida2 =="F":
  F = (temp_int*9/5)+32
  print( nome_usuario, temp,"°",unidade_medida1, " é equivalente a", F,"°F")
else:
  print('Alguma das letras não esta no padrão da unidade de medida correta')

c